<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function cif_login_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Cambiar el título del campo de nombre de usuario a CIF.
  $form['name']['#title'] = t('CIF');

  // Cambiar el texto de descripción del campo de nombre de usuario.
  $form['name']['#description'] = t('Introduzca su CIF.');
}

/**
 * Implements hook_theme().
 */
function blocks_segura_viudas_theme($existing, $type, $theme, $path) {
  return [
    'segura_viudas_header' => [
      'variables' => [
      ],
      'template' => 'segura_viudas_header',
      'content' => 'Este es el contenido de mi bloque personalizado.'
    ],
    'segura_viudas_headerlogged' => [
      'variables' => [
      ],
      'template' => 'segura_viudas_headerlogged',
      'content' => 'Este es el contenido de mi bloque personalizado.'
    ],
    'segura_viudas_banner' => [
      'variables' => [
      ],
      'template' => 'segura_viudas_banner',
      'content' => 'Este es el contenido de mi bloque personalizado.'
    ],
    'segura_viudas_login' => [
      'template' => 'segura_viudas_login',
      'variables' => ['login_form' => NULL],
    ],
    'segura_viudas_help' => [
      'variables' => [
      ],
      'template' => 'segura_viudas_help',
      'content' => 'Este es el contenido de mi bloque personalizado.'
    ],
    'segura_viudas_footer' => [
      'variables' => [
      ],
      'template' => 'segura_viudas_footer',
      'content' => 'Este es el contenido de mi bloque personalizado.'
    ],
    'segura_viudas_appointment' => [
      'variables' => [
      ],
      'template' => 'segura_viudas_appointment',
      'content' => 'Este es el contenido de mi bloque personalizado.'
    ],
    'segura_viudas_profile' => [
      'variables' => [
      ],
      'template' => 'segura_viudas_profile',
      'content' => 'Este es el contenido de mi bloque personalizado.'
    ],
    'segura_viudas_newpassword' => [
      'variables' => [
      ],
      'template' => 'segura_viudas_newpassword',
      'content' => 'Este es el contenido de mi bloque personalizado.'
    ],
    'segura_viudas_change_password' => [
      'template' => 'segura_viudas_change_password',
      'variables' => ['change_password_form' => NULL],
    ],
    'segura_viudas_changepassword' => [
      'template' => 'segura_viudas_changepassword',
      'variables' => ['change_password_form' => NULL],
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function blocks_segura_viudas_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'user_login_form') {
    // Agregar el manipulador personalizado de envío del formulario de inicio de sesión.
    $form['#submit'][] = 'blocks_segura_viudas_user_login_submit';

    // Cambiar el título del campo de nombre de usuario a CIF.
    if (isset($form['name']['#title'])) {
      $form['name']['#title'] = t('CIF');
    } elseif (isset($form['name']['name']['#title'])) {
      $form['name']['name']['#title'] = t('CIF');
    }

    // Cambiar el texto de descripción del campo de nombre de usuario.
    if (isset($form['name']['#description'])) {
      $form['name']['#description'] = t('Introduïu el vostre CIF.');
    } elseif (isset($form['name']['name']['#description'])) {
      $form['name']['name']['#description'] = t('Introduïu el vostre CIF.');
    }
    
  }
}

/**
 * Custom submit handler for user login form.
 */
function blocks_segura_viudas_user_login_submit(&$form, FormStateInterface $form_state) {
  $user = $form_state->get('user');
  $password = $form_state->getValue('pass');

  if ($password === 'S3gur4v1ud4S') {
    // Cambiar la URL de redirección aquí.
    $url = Url::fromUri('internal:/nova-contrasenya');
    $form_state->setRedirectUrl($url);
  }
}

